/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by scripts/generate-feature-keys.ts
 *
 * To regenerate:  npm run generate:feature-keys
 * 
 * NOTE: This is the initial placeholder. Run the generation script against your
 * database to populate the real values. Until then, FeatureKey is `string` so
 * existing code continues to compile.
 */

// ============================================================================
// Feature Key Union Type
// ============================================================================

/**
 * All valid feature keys in the database.
 * Used to type-check ROUTE_TO_FEATURE and ACTION_TO_FEATURE registries.
 * 
 * Run `npm run generate:feature-keys` to replace this placeholder with
 * the real union type from your feature_entitlements table.
 */
export type FeatureKey =
    | 'announcements'
    | 'dashboard'
    | 'event_scheduling'
    | 'fee_management'
    | 'messaging'
    | 'multi_role_support'
    | 'onboarding'
    | 'organization_settings'
    | 'payment_processing'
    | 'registration_forms'
    | 'roster_management'
    | 'settings'
    | 'stripe_integration'
    | 'team_management'
    | 'ticketing'
    | 'travel_details'
    | 'travel_planning'
    | 'trialexpired'
    | 'tryouts'
    | 'uniform_orders';

// ============================================================================
// Feature Key Set (runtime validation)
// ============================================================================

/** Set of all valid feature keys for runtime checks */
export const VALID_FEATURE_KEYS: ReadonlySet<string> = new Set([
    'announcements',
    'dashboard',
    'event_scheduling',
    'fee_management',
    'messaging',
    'multi_role_support',
    'onboarding',
    'organization_settings',
    'payment_processing',
    'registration_forms',
    'roster_management',
    'settings',
    'stripe_integration',
    'team_management',
    'ticketing',
    'travel_details',
    'travel_planning',
    'trialexpired',
    'tryouts',
    'uniform_orders',
]);

// ============================================================================
// Feature Metadata (from DB snapshot)
// ============================================================================

export interface FeatureKeyMetadata {
    readonly key: FeatureKey;
    readonly displayName: string;
    readonly category: string;
    readonly gateAction: string;
    readonly rolloutStatus: string;
}

/** Metadata for every feature key — useful for admin tooling */
export const FEATURE_KEY_METADATA: ReadonlyMap<FeatureKey, FeatureKeyMetadata> = new Map([
    ['announcements', { key: 'announcements', displayName: 'Announcements', category: 'Messaging & Communication', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['dashboard', { key: 'dashboard', displayName: 'Dashboard', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['event_scheduling', { key: 'event_scheduling', displayName: 'Event Scheduling', category: 'Scheduling & Calendar', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['fee_management', { key: 'fee_management', displayName: 'Fee Management', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['messaging', { key: 'messaging', displayName: 'Messaging', category: 'Messaging & Communication', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['multi_role_support', { key: 'multi_role_support', displayName: 'Multi-Role Support', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['onboarding', { key: 'onboarding', displayName: 'Onboarding', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['organization_settings', { key: 'organization_settings', displayName: 'Organization Settings', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['payment_processing', { key: 'payment_processing', displayName: 'Payment Processing', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['registration_forms', { key: 'registration_forms', displayName: 'Registration Forms', category: 'Registration & Forms', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['roster_management', { key: 'roster_management', displayName: 'Roster Management', category: 'Teams & Rosters', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['settings', { key: 'settings', displayName: 'Settings', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['stripe_integration', { key: 'stripe_integration', displayName: 'Stripe Integration', category: 'Integrations', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['team_management', { key: 'team_management', displayName: 'Team Management', category: 'Teams & Rosters', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['ticketing', { key: 'ticketing', displayName: 'Ticketing', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['travel_details', { key: 'travel_details', displayName: 'Travel Details', category: 'Travel', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['travel_planning', { key: 'travel_planning', displayName: 'Travel Planning', category: 'Travel', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['trialexpired', { key: 'trialexpired', displayName: 'Trial Expired', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['tryouts', { key: 'tryouts', displayName: 'Tryouts', category: 'Tryouts', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['uniform_orders', { key: 'uniform_orders', displayName: 'Uniform Orders', category: 'Uniforms & Gear', gateAction: 'hide', rolloutStatus: 'hidden' }],
]);

/**
 * Type guard: checks if a string is a valid FeatureKey
 */
export function isValidFeatureKey(key: string): key is FeatureKey {
    return VALID_FEATURE_KEYS.has(key);
}
