/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by scripts/generate-feature-keys.ts
 *
 * To regenerate:  npm run generate:feature-keys
 * 
 * NOTE: This is the initial placeholder. Run the generation script against your
 * database to populate the real values. Until then, FeatureKey is `string` so
 * existing code continues to compile.
 */

// ============================================================================
// Feature Key Union Type
// ============================================================================

/**
 * All valid feature keys in the database.
 * Used to type-check ROUTE_TO_FEATURE and ACTION_TO_FEATURE registries.
 * 
 * Run `npm run generate:feature-keys` to replace this placeholder with
 * the real union type from your feature_entitlements table.
 */
export type FeatureKey =
    | 'announcements'
    | 'dashboard'
    | 'event_scheduling'
    | 'facilities_detail'
    | 'facilities_list'
    | 'facilities_schedule'
    | 'fee_management'
    | 'invitations'
    | 'messaging'
    | 'multi_role_support'
    | 'onboarding'
    | 'organization_settings'
    | 'payment_processing'
    | 'photos_create'
    | 'photos_detail'
    | 'photos_gallery'
    | 'photos_gallery_manage'
    | 'photos_list'
    | 'photos_photo'
    | 'registration_forms'
    | 'reports_builder'
    | 'reports_domain_communications'
    | 'reports_domain_operations'
    | 'reports_domain_participation'
    | 'reports_domain_payments'
    | 'reports_domain_scheduling'
    | 'reports_domain_travel'
    | 'reports_domain_uniforms'
    | 'reports_events'
    | 'reports_exports'
    | 'reports_overview'
    | 'reports_registration'
    | 'reports_saved'
    | 'reports_schedules'
    | 'reports_ticketing'
    | 'reports_video'
    | 'reports_viewer'
    | 'roster_management'
    | 'settings'
    | 'stripe_integration'
    | 'team_management'
    | 'ticketing'
    | 'travel_details'
    | 'travel_planning'
    | 'trialexpired'
    | 'tryouts'
    | 'uniform_orders';

// ============================================================================
// Feature Key Set (runtime validation)
// ============================================================================

/** Set of all valid feature keys for runtime checks */
export const VALID_FEATURE_KEYS: ReadonlySet<string> = new Set([
    'announcements',
    'dashboard',
    'event_scheduling',
    'facilities_detail',
    'facilities_list',
    'facilities_schedule',
    'fee_management',
    'invitations',
    'messaging',
    'multi_role_support',
    'onboarding',
    'organization_settings',
    'payment_processing',
    'photos_create',
    'photos_detail',
    'photos_gallery',
    'photos_gallery_manage',
    'photos_list',
    'photos_photo',
    'registration_forms',
    'reports_builder',
    'reports_domain_communications',
    'reports_domain_operations',
    'reports_domain_participation',
    'reports_domain_payments',
    'reports_domain_scheduling',
    'reports_domain_travel',
    'reports_domain_uniforms',
    'reports_events',
    'reports_exports',
    'reports_overview',
    'reports_registration',
    'reports_saved',
    'reports_schedules',
    'reports_ticketing',
    'reports_video',
    'reports_viewer',
    'roster_management',
    'settings',
    'stripe_integration',
    'team_management',
    'ticketing',
    'travel_details',
    'travel_planning',
    'trialexpired',
    'tryouts',
    'uniform_orders',
]);

// ============================================================================
// Feature Metadata (from DB snapshot)
// ============================================================================

export interface FeatureKeyMetadata {
    readonly key: FeatureKey;
    readonly displayName: string;
    readonly category: string;
    readonly gateAction: string;
    readonly rolloutStatus: string;
}

/** Metadata for every feature key — useful for admin tooling */
export const FEATURE_KEY_METADATA: ReadonlyMap<FeatureKey, FeatureKeyMetadata> = new Map([
    ['announcements', { key: 'announcements', displayName: 'Announcements', category: 'Messaging & Communication', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['dashboard', { key: 'dashboard', displayName: 'Dashboard', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['event_scheduling', { key: 'event_scheduling', displayName: 'Event Scheduling', category: 'Scheduling & Calendar', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['fee_management', { key: 'fee_management', displayName: 'Fee Management', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['messaging', { key: 'messaging', displayName: 'Messaging', category: 'Messaging & Communication', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['multi_role_support', { key: 'multi_role_support', displayName: 'Multi-Role Support', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['onboarding', { key: 'onboarding', displayName: 'Onboarding', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['organization_settings', { key: 'organization_settings', displayName: 'Organization Settings', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['payment_processing', { key: 'payment_processing', displayName: 'Payment Processing', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['registration_forms', { key: 'registration_forms', displayName: 'Registration Forms', category: 'Registration & Forms', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['roster_management', { key: 'roster_management', displayName: 'Roster Management', category: 'Teams & Rosters', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['settings', { key: 'settings', displayName: 'Settings', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['stripe_integration', { key: 'stripe_integration', displayName: 'Stripe Integration', category: 'Integrations', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['team_management', { key: 'team_management', displayName: 'Team Management', category: 'Teams & Rosters', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['ticketing', { key: 'ticketing', displayName: 'Ticketing', category: 'Payments', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['travel_details', { key: 'travel_details', displayName: 'Travel Details', category: 'Travel', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['travel_planning', { key: 'travel_planning', displayName: 'Travel Planning', category: 'Travel', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['trialexpired', { key: 'trialexpired', displayName: 'Trial Expired', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['tryouts', { key: 'tryouts', displayName: 'Tryouts', category: 'Tryouts', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['uniform_orders', { key: 'uniform_orders', displayName: 'Uniform Orders', category: 'Uniforms & Gear', gateAction: 'hide', rolloutStatus: 'hidden' }],
    // Registry-only keys (metadata placeholders until DB sync)
    ['facilities_list', { key: 'facilities_list', displayName: 'Facilities List', category: 'Facilities', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['facilities_detail', { key: 'facilities_detail', displayName: 'Facilities Detail', category: 'Facilities', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['facilities_schedule', { key: 'facilities_schedule', displayName: 'Facilities Schedule', category: 'Facilities', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['invitations', { key: 'invitations', displayName: 'Invitations', category: 'Admin & Permissions', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_list', { key: 'photos_list', displayName: 'Photos List', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_create', { key: 'photos_create', displayName: 'Photos Create', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_detail', { key: 'photos_detail', displayName: 'Photos Detail', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_photo', { key: 'photos_photo', displayName: 'Photos Photo', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_gallery', { key: 'photos_gallery', displayName: 'Photos Gallery', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['photos_gallery_manage', { key: 'photos_gallery_manage', displayName: 'Photos Gallery Manage', category: 'Photos', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_overview', { key: 'reports_overview', displayName: 'Reports Overview', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_builder', { key: 'reports_builder', displayName: 'Reports Builder', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_saved', { key: 'reports_saved', displayName: 'Reports Saved', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_exports', { key: 'reports_exports', displayName: 'Reports Exports', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_schedules', { key: 'reports_schedules', displayName: 'Reports Schedules', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_viewer', { key: 'reports_viewer', displayName: 'Reports Viewer', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_ticketing', { key: 'reports_ticketing', displayName: 'Reports Ticketing', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_registration', { key: 'reports_registration', displayName: 'Reports Registration', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_video', { key: 'reports_video', displayName: 'Reports Video', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_events', { key: 'reports_events', displayName: 'Reports Events', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_participation', { key: 'reports_domain_participation', displayName: 'Reports Domain Participation', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_payments', { key: 'reports_domain_payments', displayName: 'Reports Domain Payments', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_scheduling', { key: 'reports_domain_scheduling', displayName: 'Reports Domain Scheduling', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_travel', { key: 'reports_domain_travel', displayName: 'Reports Domain Travel', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_uniforms', { key: 'reports_domain_uniforms', displayName: 'Reports Domain Uniforms', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_communications', { key: 'reports_domain_communications', displayName: 'Reports Domain Communications', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
    ['reports_domain_operations', { key: 'reports_domain_operations', displayName: 'Reports Domain Operations', category: 'Reports', gateAction: 'overlay', rolloutStatus: 'live' }],
]);

/**
 * Type guard: checks if a string is a valid FeatureKey
 */
export function isValidFeatureKey(key: string): key is FeatureKey {
    return VALID_FEATURE_KEYS.has(key);
}
