/**
 * Database Types Placeholder
 * 
 * This file should be auto-generated by Supabase CLI using:
 * npx supabase gen types typescript --project-id [YOUR_PROJECT_ID] > src/lib/database.types.ts
 * 
 * For now, we export a placeholder type to prevent TypeScript errors.
 * The actual Database type should match your Supabase schema.
 */

// Placeholder Database type
// TODO: Replace with actual Supabase generated types
export type Database = {
    public: {
        Tables: {
            [key: string]: {
                Row: Record<string, unknown>
                Insert: Record<string, unknown>
                Update: Record<string, unknown>
            }
        }
        Views: Record<string, never>
        Functions: Record<string, never>
        Enums: Record<string, never>
    }
}
