/**
 * Route paths and navigation constants
 */

// Route keys (for type-safe route references)
export const ROUTE_KEYS = {
  HOME: 'home',
  LOGIN: 'auth.login',
  SIGNUP: 'auth.signup',
  FORGOT_PASSWORD: 'auth.forgotPassword',
  RESET_PASSWORD: 'auth.resetPassword',
  ACCEPT_INVITE: 'auth.acceptInvite',
  AUTH_CALLBACK: 'auth.authCallback',
  CONFIRM_EMAIL: 'auth.confirmEmail',
  UNAUTHORIZED: 'auth.unauthorized',
  
  PORTAL_DASHBOARD: 'portal.dashboard',
  PORTAL_SETTINGS: 'portal.settings',
  PORTAL_ATHLETES: 'portal.athletes',
  PORTAL_CALENDAR: 'portal.calendar',
  PORTAL_PAYMENTS: 'portal.payments',
  PORTAL_UNIFORMS: 'portal.uniforms',
  PORTAL_TRAVEL: 'portal.travel',
  PORTAL_TRYOUTS: 'portal.tryouts',
  PORTAL_MESSAGES: 'portal.messages',
  PORTAL_PHOTOS: 'portal.photos',
  PORTAL_VIDEOS: 'portal.videos',
  PORTAL_MY_TICKETS: 'portal.myTickets',
  
  ADMIN_DASHBOARD: 'admin.dashboard',
  ADMIN_SPORTS: 'admin.sports',
  ADMIN_TEAMS: 'admin.teams',
  ADMIN_ATHLETES: 'admin.athletes',
  ADMIN_EVENTS: 'admin.events',
  ADMIN_PHOTOS: 'admin.photos',
  ADMIN_PAYMENTS: 'admin.payments',
  ADMIN_SETTINGS: 'admin.settings',
  ADMIN_ANNOUNCEMENTS: 'admin.announcements',
  ADMIN_ATTENDANCE: 'admin.attendance',
  ADMIN_TICKETING_EVENTS: 'admin.ticketingEvents',
  ADMIN_TICKETING_ORDERS: 'admin.ticketingOrders',
  ADMIN_UNIFORMS: 'admin.uniforms',
  ADMIN_TRAVEL: 'admin.travel',
  ADMIN_TRYOUTS: 'admin.tryouts',
  ADMIN_ORGANIZATION: 'admin.organization',
  ADMIN_USERS: 'admin.users',
  ADMIN_NOTIFICATIONS: 'admin.notifications',
  
  PLATFORM_DASHBOARD: 'platform.dashboard',
  PLATFORM_ORGANIZATIONS: 'platform.organizations',
  PLATFORM_USERS: 'platform.users',
  PLATFORM_STRUCTURE: 'platform.structure',
  PLATFORM_PAYMENTS: 'platform.payments',
  PLATFORM_FEES: 'platform.fees',
  PLATFORM_AUDIT: 'platform.audit',
  PLATFORM_FEATURE_FLAGS: 'platform.featureFlags',
  PLATFORM_ADMINS: 'platform.admins',
  PLATFORM_LICENSES: 'platform.licenses',
  PLATFORM_EMAIL_SETTINGS: 'platform.emailSettings',
  PLATFORM_PHOTOS: 'platform.photos',
  PLATFORM_TICKETING: 'platform.ticketing',
} as const

export type RouteKey = typeof ROUTE_KEYS[keyof typeof ROUTE_KEYS]

// Route paths
export const ROUTES = {
  HOME: '/',
  LOGIN: '/portal/login',
  SIGNUP: '/portal/signup',
  FORGOT_PASSWORD: '/portal/forgot-password',
  RESET_PASSWORD: '/portal/reset-password',
  ACCEPT_INVITE: '/portal/accept-invite',
  AUTH_CALLBACK: '/portal/auth/callback',
  CONFIRM_EMAIL: '/portal/confirm-email',
  UNAUTHORIZED: '/portal/unauthorized',
  
  // Portal routes
  PORTAL_DASHBOARD: '/portal/dashboard',
  PORTAL_SETTINGS: '/portal/settings',
  PORTAL_ATHLETES: '/portal/athletes',
  PORTAL_ATHLETE_CREATE: '/portal/athletes/new',
  PORTAL_ATHLETE_PROFILE: (id: string) => `/portal/athletes/${id}/profile`,
  PORTAL_ATHLETE_EDIT: (id: string) => `/portal/athletes/${id}/edit`,
  PORTAL_CALENDAR: '/portal/calendar',
  PORTAL_EVENT_CREATE: '/portal/calendar/new',
  PORTAL_EVENT_EDIT: (id: string) => `/portal/calendar/events/${id}/edit`,
  PORTAL_EVENT_DETAIL: (id: string) => `/portal/calendar/events/${id}`,
  PORTAL_PAYMENTS: '/portal/payments',
  PORTAL_PAYMENT_DETAIL: (id: string) => `/portal/payments/${id}`,
  PORTAL_PAYMENT_SUCCESS: '/portal/payments/success',
  PORTAL_PAYMENT_CANCEL: '/portal/payments/cancel',
  PORTAL_UNIFORMS: '/portal/uniforms',
  PORTAL_UNIFORM_KIT: (kitId: string) => `/portal/uniforms/${kitId}`,
  PORTAL_TRAVEL: '/portal/travel',
  PORTAL_TRAVEL_DETAIL: (id: string) => `/portal/travel/${id}`,
  PORTAL_TRYOUTS: '/portal/tryouts',
  PORTAL_TRYOUT_DETAIL: (tryoutId: string) => `/portal/tryouts/${tryoutId}`,
  PORTAL_MESSAGES: '/portal/huddles/announcements',
  PORTAL_MESSAGE_DETAIL: (announcementId: string) => `/portal/messages/${announcementId}`,
  PORTAL_PHOTOS: '/portal/photos',
  PORTAL_PHOTO_GALLERY: (id: string) => `/portal/photos/gallery/${id}`,
  PORTAL_PHOTO_GALLERY_MANAGE: (id: string) => `/portal/photos/gallery/${id}/manage`,
  PORTAL_VIDEOS: '/portal/videos',
  PORTAL_VIDEO_DETAIL: (id: string) => `/portal/videos/${id}`,
  PORTAL_MY_TICKETS: '/portal/account/tickets',
  PORTAL_NOTIFICATIONS: '/portal/notifications',
  PORTAL_JOIN_TEAM: '/portal/join',
  PORTAL_ROLE_SELECTION: '/portal/role-selection',
  
  // Admin routes
  ADMIN_ROOT: '/admin',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_SPORTS: '/admin/sports',
  ADMIN_SPORT_DETAIL: (slug: string) => `/admin/sports/${slug}`,
  ADMIN_SPORT_UPDATE: (slug: string) => `/admin/sports/${slug}/update`,
  ADMIN_TEAMS: '/admin/teams',
  ADMIN_TEAM_DETAIL: (id: string) => `/admin/teams/${id}`,
  ADMIN_TEAM_UPDATE: (id: string) => `/admin/teams/${id}/update`,
  ADMIN_ATHLETES: '/admin/athletes',
  ADMIN_ATHLETE_DETAIL: (id: string) => `/admin/athletes/${id}`,
  ADMIN_ATHLETE_EDIT: (id: string) => `/admin/athletes/${id}/edit`,
  ADMIN_ATHLETE_CREATE: '/admin/athletes/new',
  ADMIN_ATHLETE_IMPORT: '/admin/athletes/import',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_EVENT_CREATE: '/admin/events/new',
  ADMIN_EVENT_EDIT: (id: string) => `/admin/events/${id}/edit`,
  ADMIN_EVENT_ATTENDANCE: (id: string) => `/admin/events/${id}/attendance`,
  ADMIN_PHOTOS: '/admin/photos',
  ADMIN_PHOTO_DETAIL: (id: string) => `/admin/photos/${id}`,
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_PAYMENT_DETAIL: (id: string) => `/admin/payments/${id}`,
  ADMIN_FEE_CREATE: '/admin/payments/new',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SPORT_SETTINGS: '/admin/settings/sport-profiles',
  ADMIN_ANNOUNCEMENTS: '/admin/announcements',
  ADMIN_ATTENDANCE: '/admin/attendance',
  ADMIN_UNIFORMS: '/admin/uniforms',
  ADMIN_UNIFORM_CREATE: '/admin/uniforms/new',
  ADMIN_UNIFORM_EDIT: (id: string) => `/admin/uniforms/${id}/edit`,
  ADMIN_TRAVEL: '/admin/travel',
  ADMIN_TRAVEL_CREATE: '/admin/travel/new',
  ADMIN_TRAVEL_EDIT: (id: string) => `/admin/travel/${id}`,
  ADMIN_TRYOUTS: '/admin/tryouts',
  ADMIN_TRYOUT_CREATE: '/admin/tryouts/new',
  ADMIN_TRYOUT_DETAIL: (tryoutId: string) => `/admin/tryouts/${tryoutId}`,
  ADMIN_ORGANIZATION: '/admin/organization',
  ADMIN_ORGANIZATION_OVERVIEW: '/admin/organization/overview',
  ADMIN_ORGANIZATION_USERS: '/admin/organization/users',
  ADMIN_ORGANIZATION_BILLING: '/admin/organization/billing',
  ADMIN_ORGANIZATION_FORMS: '/admin/organization/forms',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_CREATE: '/admin/users/new',
  ADMIN_USER_EDIT: (id: string) => `/admin/users/${id}`,
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_FAMILIES: '/admin/guardians',
  ADMIN_FAMILY_CREATE: '/admin/guardians/new',
  ADMIN_FAMILY_DETAIL: (id: string) => `/admin/guardians/${id}`,
  ADMIN_CHILD_CREATE: '/admin/guardians/:familyId/athletes/new',
  ADMIN_GUARDIAN_REQUESTS: '/admin/guardian-requests',
  ADMIN_ONBOARDING: '/admin/onboarding',
  ADMIN_TRIAL_EXPIRED: '/admin/organization/trial-expired',
  ADMIN_BILLING_PLAN_SELECTION: '/admin/organization/billing/plan-selection',
  ADMIN_BILLING_CHECKOUT_SUCCESS: '/admin/organization/billing/checkout/success',
  ADMIN_BILLING_CHECKOUT_CANCEL: '/admin/organization/billing/checkout/cancel',
  ADMIN_TICKETING_SCANNER: '/admin/ticketing/scanner',
  ADMIN_TICKETING_EVENTS: '/admin/ticketing/events',
  ADMIN_TICKETING_EVENT_CREATE: '/admin/ticketing/events/new',
  ADMIN_TICKETING_ORDERS: '/admin/ticketing/orders',
  ADMIN_TICKETING_ORDER_DETAIL: (orderId: string) => `/admin/ticketing/orders/${orderId}`,
  ADMIN_PROGRAMS: '/admin/programs',
  ADMIN_PROGRAM_DETAIL: (id: string) => `/admin/programs/${id}`,
  ADMIN_PROGRAM_UPDATE: (id: string) => `/admin/programs/${id}/update`,
  ADMIN_LEVELS: '/admin/levels',
  ADMIN_LEVEL_DETAIL: (id: string) => `/admin/levels/${id}`,
  ADMIN_LEVEL_UPDATE: (id: string) => `/admin/levels/${id}/update`,
  ADMIN_SEASONS: '/admin/seasons',
  ADMIN_SEASON_DETAIL: (id: string) => `/admin/seasons/${id}`,
  ADMIN_SEASON_UPDATE: (id: string) => `/admin/seasons/${id}/update`,
  ADMIN_ROSTER: (id: string) => `/admin/teams/${id}/roster`,
  
  // Platform admin routes
  PLATFORM_ROOT: '/platform-admin',
  PLATFORM_DASHBOARD: '/platform-admin',
  PLATFORM_ORGANIZATIONS: '/platform-admin/organizations',
  PLATFORM_ORGANIZATION_DETAIL: (id: string) => `/platform-admin/organizations/${id}`,
  PLATFORM_USERS: '/platform-admin/users',
  PLATFORM_USER_DETAIL: (id: string) => `/platform-admin/users/${id}`,
  PLATFORM_STRUCTURE: '/platform-admin/structure',
  PLATFORM_PAYMENTS: '/platform-admin/payments',
  PLATFORM_FEES: '/platform-admin/fees',
  PLATFORM_AUDIT: '/platform-admin/audit',
  PLATFORM_FEATURE_FLAGS: '/platform-admin/feature-flags',
  PLATFORM_FEATURE_FLAG_DETAIL: (id: string) => `/platform-admin/feature-flags/${id}`,
  PLATFORM_ADMINS: '/platform-admin/admins',
  PLATFORM_LICENSES: '/platform-admin/licenses',
  PLATFORM_LICENSE_TIERS: '/platform-admin/licenses/tiers',
  PLATFORM_LICENSE_TIER_DETAIL: (id: string) => `/platform-admin/licenses/tiers/${id}`,
  PLATFORM_LICENSE_FEATURES: '/platform-admin/licenses/features',
  PLATFORM_LICENSE_FEATURE_DETAIL: (id: string) => `/platform-admin/licenses/features/${id}`,
  PLATFORM_LICENSE_OVERRIDES: '/platform-admin/licenses/overrides',
  PLATFORM_LICENSE_OVERRIDE_CREATE: '/platform-admin/licenses/overrides/new',
  PLATFORM_LICENSE_OVERRIDE_DETAIL: (id: string) => `/platform-admin/licenses/overrides/${id}`,
  PLATFORM_LICENSE_AUDIT: '/platform-admin/licenses/audit',
  PLATFORM_EMAIL_SETTINGS: '/platform-admin/email-settings',
  PLATFORM_PHOTOS: '/platform-admin/photos',
  PLATFORM_PHOTOS_CONTENT_REVIEW: '/platform-admin/photos/content-review',
  PLATFORM_PHOTOS_STORAGE: '/platform-admin/photos/storage',
  PLATFORM_TICKETING_EVENTS: '/platform-admin/ticketing/events',
  PLATFORM_TICKETING_ORDERS: '/platform-admin/ticketing/orders',
  PLATFORM_TICKETING_WEBHOOKS: '/platform-admin/ticketing/webhooks',
  PLATFORM_TICKETING_ORG_DASHBOARD: (id: string) => `/platform-admin/ticketing/organizations/${id}`,
  
  // Public routes
  PUBLIC_ORG_LANDING: (slug: string) => `/o/${slug}`,
  PUBLIC_ORG_TICKETS: (slug: string) => `/o/${slug}/tickets`,
  PUBLIC_ORG_TICKET_EVENT: (slug: string, eventId: string) => `/o/${slug}/tickets/events/${eventId}`,
  PUBLIC_ORG_TICKET_ORDER: (slug: string, orderId: string) => `/o/${slug}/tickets/order/${orderId}`,
  PUBLIC_ORG_TICKET_ACCESS: (slug: string, token: string) => `/o/${slug}/tickets/access/${token}`,
  
  // Public ticketing routes
  PUBLIC_TICKETS: '/portal/tickets',
  PUBLIC_TICKET_EVENT: (eventId: string) => `/portal/tickets/events/${eventId}`,
  PUBLIC_TICKET_ORDER: (orderId: string) => `/portal/tickets/order/${orderId}`,
  PUBLIC_TICKET_ACCESS: (token: string) => `/portal/tickets/access/${token}`,
  PUBLIC_TICKET_VALIDATE: (token: string) => `/portal/tickets/validate/${token}`,
} as const

// Public URL helpers
export const PUBLIC_URL_BASE = 'https://youthsports.team'
export const PUBLIC_URL_ORG_PATH = (slug: string) => `${PUBLIC_URL_BASE}/o/${slug}`
export const PUBLIC_URL_ORG_TICKETS = (slug: string) => `${PUBLIC_URL_BASE}/o/${slug}/tickets`
