$ErrorActionPreference = 'Stop'

function Split-List {
  param([string]$Text)
  if ([string]::IsNullOrWhiteSpace($Text)) { return @() }
  return $Text -split '\|' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }
}

function To-Li {
  param([string[]]$Items)
  return ($Items | ForEach-Object { "<li>$_</li>" }) -join "`n"
}

function Build-Content {
  param([pscustomobject]$a)

  $before = To-Li (Split-List $a.Before)
  $steps = To-Li (Split-List $a.Steps)
  $deps = To-Li (Split-List $a.Dependencies)
  $access = To-Li (Split-List $a.Access)
  $edges = To-Li (Split-List $a.EdgeCases)
  $done = To-Li (Split-List $a.DoneRight)

  return @"
<h1>$($a.Title)</h1>
<p>$($a.Intro)</p>
<p>This article is written for real YouthSports workflows, not generic software steps.</p>

<h2>Before you start</h2>
<ul>
$before
</ul>

<h2>Step-by-step workflow</h2>
<ol>
$steps
</ol>

<h2>What controls this workflow</h2>
<ul>
$deps
</ul>

<h2>Access and visibility rules</h2>
<ul>
$access
</ul>

<h2>Common edge cases and fast fixes</h2>
<ul>
$edges
</ul>

<h2>You are done when</h2>
<ul>
$done
</ul>

<p>YouthSports is designed to keep family logistics clear, fast, and reliable across the season.</p>
"@
}

$date = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

$articles = @(
  [pscustomobject]@{ Title='Join a Team with an Invite Code'; Slug='join-a-team-with-an-invite-code'; Section='Getting Started'; Tags='guardians,teams,invite-codes,athletes,seasons,rosters,join'; Excerpt='Use an invite code to link your athlete to the right team.'; Intro='Invite code join is the fastest path from onboarding to active roster placement.'; Before='Get an active code from coach or admin.|Sign in, or be ready to sign in and return.|Make sure athlete profile exists in My Athletes.'; Steps='Open /portal/join and enter code.|If prompted, sign in or sign up and continue.|Review team and choose athlete and season.|Submit join request.|Open My Athletes and confirm team context appears.'; Dependencies='Code must be valid and active.|Season must be available.|Duplicate membership blocks creation.|Capacity checks can block completion.'; Access='Route is public, submit requires authentication.|Flow is guardian focused because child selection is required.|Feature visibility still depends on entitlement.'; EdgeCases='Invalid code: request a fresh code.|Too many attempts: wait and retry once.|No child shown: create athlete first.|Already member: ask staff to resolve membership state.'; DoneRight='Athlete has active membership in target team and season.|Calendar and team surfaces reflect the new context.|No unresolved join errors remain.' },
  [pscustomobject]@{ Title='Join from a Secure Team Invitation Link'; Slug='join-from-a-secure-team-invitation-link'; Section='Getting Started'; Tags='guardians,join-link,invitations,teams,seasons,approval'; Excerpt='Use secure join links for auto-approved or pending requests.'; Intro='Secure join links preserve context through sign in, athlete selection, and approval.'; Before='Open the exact invitation URL.|Stay in same tab through auth.|Confirm athlete profile exists first.'; Steps='Open /portal/join/link?token=...|Allow token validation.|Sign in or sign up if needed.|Select athlete and season.|Submit and review Approved or Pending status.'; Dependencies='Token must be valid and unexpired.|Some links auto-approve, others require review.|Season options depend on org setup.|Duplicate or full team rules still apply.'; Access='Link can be opened while signed out.|Submission requires authenticated user context.|Final status is policy controlled by org.'; EdgeCases='Expired token: request a new link.|Already joined: no new request needed.|Network timeout: retry on stable connection.|No season option: ask staff to verify active seasons.'; DoneRight='Request ends without active error.|Athlete enters team context after approval.|No duplicate profile is created.' },
  [pscustomobject]@{ Title='Create an Athlete Profile and Link Guardians in One Flow'; Slug='create-an-athlete-profile-and-link-guardians-in-one-flow'; Section='Getting Started'; Tags='guardians,athletes,profiles,guardian-linking,medical,rosters'; Excerpt='Build one complete athlete profile with guardian links from day one.'; Intro='A complete athlete profile powers schedules, payments, and communications correctly.'; Before='Prepare legal name and birthdate.|Have medical and emergency details ready.|Collect additional guardian email if needed.'; Steps='Open /portal/athletes/new.|Enter required profile details.|Add optional contact and health details.|Add optional additional guardian.|Choose sports played or interested.|Submit and verify athlete appears in list.'; Dependencies='Current user auto-links as guardian.|Additional guardian email is validated and matched.|Phone and email formats are validated.|Photo upload can fail without blocking create.'; Access='Route is parent-only in portal.|Linking is org scoped.|Sports options come from system sports setup.'; EdgeCases='Invalid birthdate: correct and retry.|Same guardian email as yours: use another email.|Invalid phone or email: fix format.|Photo upload error: upload later from profile.'; DoneRight='Athlete appears in My Athletes.|Guardian links reflect expected ownership.|No duplicate athlete exists.' },
  [pscustomobject]@{ Title='Request Attachment to an Existing Athlete Profile'; Slug='request-attachment-to-an-existing-athlete-profile'; Section='Getting Started'; Tags='guardians,athletes,attachment,approvals,rosters,organizations'; Excerpt='Attach to an existing athlete profile without creating duplicates.'; Intro='Attachment requests protect roster quality while adding the right guardian access.'; Before='Know athlete name as stored in org.|Choose correct organization if you have multiple.|Use at least two search characters.'; Steps='Open /portal/athletes/request-attachment.|Select organization and search athlete.|Review result details.|Submit request.|Track pending, approved, denied, or expired status.|Resubmit only when denied or expired.'; Dependencies='Parent role in selected org is required.|Approval is admin controlled.|Request state is tracked per athlete.|Expired requests can be resubmitted.'; Access='Route is parent only.|Search scope is limited to attachable athletes.|Only approved requests grant direct access.'; EdgeCases='No match: broaden search term.|Pending exists: wait for review.|Denied: resolve reason then resubmit.|Approved already: no new request required.'; DoneRight='Attachment is approved or clearly pending.|Athlete appears in your My Athletes view.|No duplicate profile was created.' },
  [pscustomobject]@{ Title='Invite Another Guardian and Manage Pending Invites'; Slug='invite-another-guardian-and-manage-pending-invites'; Section='Getting Started'; Tags='guardians,invites,family,permissions,settings,athletes'; Excerpt='Invite, resend, and cancel guardian invites in Family settings.'; Intro='Family operations run smoother when the right adults have access to the right child.'; Before='Open /portal/settings Family section.|Pick the correct child card.|Use a valid guardian email.'; Steps='Click Invite in child Guardians section.|Enter email and review match indicator.|Submit invite and confirm pending row.|Use Resend for missed invite emails.|Use Cancel Invite to revoke old pending requests.'; Dependencies='Invite flow checks account match first.|Pending invites and active guardians are separate states.|Invite actions refresh family data.|Actions apply per child context.'; Access='Managed by parent role users in Settings.|Child-level scope is enforced.|Org policy governs final accepted behavior.'; EdgeCases='Already linked: do not create new invite.|Invalid email: correct format.|Resend failure: retry once.|Wrong child invite: cancel and recreate.'; DoneRight='Active guardians are correct per child.|Stale pending invites are removed.|Family access mirrors real responsibilities.' },
  [pscustomobject]@{ Title='Pay Multiple Fees in One Checkout Session'; Slug='pay-multiple-fees-in-one-checkout-session'; Section='Payments'; Tags='payments,checkout,fees,discount-codes,guardians,billing'; Excerpt='Select open fees, apply discount codes, and pay in one checkout.'; Intro='YouthSports lets families clear multiple open balances in one fast checkout flow.'; Before='Open /portal/payments and review open items.|Filter by child, team, or status.|Have discount code ready if applicable.'; Steps='Select one or more open assignments.|Apply discount code and confirm validation.|Review selected total.|Click Pay to launch checkout.|Complete payment and return to payments page.'; Dependencies='Discount is validated at apply and before checkout.|Only selected assignments are sent to checkout.|Checkout session URL must be created successfully.|Balance refresh can lag briefly after payment.'; Access='Route requires parent or athlete with payment entitlement.|Assignments are scoped to your visible context.|Org billing policy controls item behavior.'; EdgeCases='No selection: choose at least one fee.|Invalid discount: remove or replace code.|Checkout failure: retry once.|Stale status: refresh after short delay.'; DoneRight='Checkout completes without validation errors.|Selected balances reduce correctly.|No unintended assignments were charged.' },
  [pscustomobject]@{ Title='Make Partial Payments Without Validation Errors'; Slug='make-partial-payments-without-validation-errors'; Section='Payments'; Tags='payments,partial-payments,billing,balances,fees,guardians'; Excerpt='Pay part of a fee while staying inside policy limits.'; Intro='Partial payment is supported when both org policy and fee settings allow it.'; Before='Find a fee with Pay Partial action.|Review minimum and remaining amount.|Enter exact amount you plan to pay now.'; Steps='Open Pay Partial from eligible fee card.|Read total, paid, and remaining values.|Enter amount between minimum and remaining.|Submit to partial checkout.|Complete payment and verify remaining balance.'; Dependencies='Org policy must allow partial payments.|Fee must allow partial payment.|Minimum is enforced at ten percent of total fee.|Amount cannot exceed remaining balance.'; Access='Partial button only appears when policy and fee flags align.|Payment entitlement still required.|Validation runs before checkout session starts.'; EdgeCases='No partial button: policy or fee flag disabled.|Amount too low: increase to minimum.|Amount too high: reduce to remaining balance.|Checkout error: retry once then contact billing.'; DoneRight='Partial payment posts successfully.|Remaining balance is reduced accurately.|Assignment status remains consistent.' },
  [pscustomobject]@{ Title='Use Payment Details, Receipts, and Billing Contact Actions'; Slug='use-payment-details-receipts-and-billing-contact-actions'; Section='Payments'; Tags='payments,receipts,billing-support,fees,history,guardians'; Excerpt='Open fee detail, download receipts, and contact billing quickly.'; Intro='Payment Detail gives line-level transparency for one assignment from charge to receipt.'; Before='Open fee detail from /portal/payments.|Check status and due date first.|Use paid assignments for receipt actions.'; Steps='Open /portal/payments/{id}.|Review total, paid, and remaining values.|Download receipt for paid assignment.|Use Contact Billing to open prefilled email.|Return and recheck status after updates.'; Dependencies='Receipt generation is paid-state dependent.|Billing contact uses org category with fallback.|Detail requires assignment access in your scope.|Recent payment sync may take a short moment.'; Access='Route is protected by payment entitlement.|Only in-scope assignments are returned.|Contact destination depends on org setup.'; EdgeCases='Receipt unavailable: verify paid status.|No billing email: org fallback may be empty.|Access denied: assignment outside scope.|Status delay: refresh after short wait.'; DoneRight='You can confirm exact assignment status.|Receipt opens for paid items.|Billing questions route correctly.' },
  [pscustomobject]@{ Title='Find Events Faster with Calendar Filters and Fan View'; Slug='find-events-faster-with-calendar-filters-and-fan-view'; Section='Events and Calendar'; Tags='calendar,events,filters,fan-view,teams,children,guardians'; Excerpt='Use filters and fan view to focus on the events that matter.'; Intro='Calendar is most useful when you control scope by child, team, event type, and fan context.'; Before='Open /portal/calendar.|Choose agenda, week, or month view.|Decide whether you need fan view.'; Steps='Set date and view mode.|Apply team, child, and type filters.|Toggle Fan View when needed.|Open event modal from list or grid.|Use View Details for full event actions.'; Dependencies='Filter state syncs to URL params.|Fan View uses a separate source feed.|Server-side filtering controls list payload.|Canceled visibility follows filter setting.'; Access='Route requires parent or athlete and entitlement.|Fan View utility depends on follows and bookmarks.|RSVP controls appear only on RSVP-enabled events.'; EdgeCases='No events: clear filters and retry.|Fan View empty: add follows or bookmarks.|Wrong date: reset to current week.|Too much noise: narrow type filter.'; DoneRight='You can isolate this week priorities quickly.|Fan and family context switch is clear.|Detail navigation keeps planning momentum.' },
  [pscustomobject]@{ Title='RSVP Correctly for General and Athlete-Specific Events'; Slug='rsvp-correctly-for-general-and-athlete-specific-events'; Section='Events and Calendar'; Tags='calendar,rsvp,athletes,attendance,events,guardians'; Excerpt='Respond once or per athlete based on event RSVP mode.'; Intro='Different events require different RSVP behavior, and YouthSports supports both modes.'; Before='Open event detail or modal.|Confirm RSVP is enabled.|Check whether mode is general or athlete-specific.'; Steps='Open RSVP area.|Use general RSVP for family-level response.|Use athlete-specific RSVP for per-child response.|Wait for save state.|Reopen event to verify persisted values.'; Dependencies='RSVP mode is event-configured by staff.|Canceled events disable RSVP updates.|Optimistic updates reconcile with server result.|Past-event windows may hide response controls.'; Access='RSVP actions require authenticated role context.|Athlete-specific actions require visible child profiles.|Disabled RSVP events show no controls.'; EdgeCases='Save failed: retry once.|Wrong child status: edit that athlete row.|No RSVP controls: disabled or canceled event.|Past lock: responses intentionally unavailable.'; DoneRight='Coach sees intended attendance signal.|Each child status is correct where needed.|No unresolved RSVP error remains.' },
  [pscustomobject]@{ Title='Use Event Details for Maps, Commute, Tickets, and Calendar Export'; Slug='use-event-details-for-maps-commute-tickets-and-calendar-export'; Section='Events and Calendar'; Tags='events,maps,commute,tickets,calendar-export,bookmarks'; Excerpt='Turn one event page into your full game day command center.'; Intro='Event Detail combines route tools, ticket links, and calendar export into one practical flow.'; Before='Open /portal/calendar/events/{eventId}.|Confirm time and venue are present.|Set a useful commute origin.'; Steps='Review event quick info and weather.|Open maps or rideshare links.|Save commute start location.|Use Google, Apple, or ICS export.|Use Get Tickets when ticket link exists.|Bookmark event for fast return.'; Dependencies='Ticket action appears only for linked ticketed events.|Commute summary needs origin and destination.|Calendar export needs valid date-time values.|Some actions are hidden for old events.'; Access='Detail route is parent and athlete accessible.|Edit/delete actions are elevated-role only.|Bookmark state follows user fan context.'; EdgeCases='No route summary: verify both addresses.|No ticket action: event may be free or unavailable.|Calendar export issue: verify event time data.|Bookmark missing: refresh bookmarks list.'; DoneRight='Directions and arrival plan are confirmed.|Event is on your personal calendar.|Ticket access plan is set before arrival.' },
  [pscustomobject]@{ Title='Build a Better Fan Feed with Follows and Bookmarks'; Slug='build-a-better-fan-feed-with-follows-and-bookmarks'; Section='Events and Calendar'; Tags='follows,bookmarks,fan-view,events,organizations,calendar'; Excerpt='Use follows and bookmarks to shape the fan events you see.'; Intro='Follows and bookmarks are the two controls that make fan activity high signal instead of noisy.'; Before='Use /portal/follows for organization follows.|Use /portal/bookmarks for saved events.|Check results in calendar Fan View.'; Steps='Follow organizations you care about.|Bookmark key events as they appear.|Unfollow organizations no longer relevant.|Remove stale bookmarks.|Open Fan View and confirm feed quality.'; Dependencies='Follows are org-level, bookmarks are event-level.|Fan View aggregates multiple fan sources.|Unfollow updates future feed composition.|Bookmark mutations refresh list queries.'; Access='Follows page is parent-only.|Bookmarks page is parent and athlete.|Fan View toggle exists in calendar for both roles.'; EdgeCases='Fan feed empty: add follows or bookmarks.|Unfollow failed: retry from confirm modal.|Bookmark removal delayed: refresh once.|Missing event: ensure it is upcoming and visible.'; DoneRight='Fan View includes the events you care about.|Saved list stays curated and current.|You can reach event detail quickly.' },
  [pscustomobject]@{ Title='Buy Tickets and Choose Seats Without Checkout Failures'; Slug='buy-tickets-and-choose-seats-without-checkout-failures'; Section='Tickets and Entry'; Tags='tickets,checkout,reserved-seating,seats,events,payments'; Excerpt='Choose ticket quantities and seats correctly before checkout.'; Intro='Ticket checkout is fast, but it validates sales windows, inventory, email, and seating rules.'; Before='Open /portal/tickets/events/{eventId}.|Confirm event is currently on sale.|Use valid purchaser email.'; Steps='Select quantity for each ticket type.|Select seats for reserved ticket types.|Review total and sale status.|Enter purchaser email.|Submit checkout and complete payment.'; Dependencies='Event must be published and not ended.|Sales windows can block checkout.|Capacity remaining limits quantity.|Reserved seating needs full and valid seat selections.'; Access='Ticket purchase pages are public.|Checkout still enforces event policy checks.|Offline device state blocks checkout start.'; EdgeCases='Sold out during selection: adjust cart and retry.|Email invalid: correct format.|Seat validation error: reselect valid seats.|Sales closed: return during active window.'; DoneRight='Checkout starts without validation errors.|Order success page confirms purchase.|Ticket delivery email is received.' },
  [pscustomobject]@{ Title='Find, Resend, and Manage Tickets After Purchase'; Slug='find-resend-and-manage-tickets-after-purchase'; Section='Tickets and Entry'; Tags='tickets,my-tickets,resend,email,orders,qr'; Excerpt='Use My Tickets to view QR codes and resend ticket emails.'; Intro='Post-purchase ticket operations are about retrieval speed and reliable delivery recovery.'; Before='Open /portal/account/tickets while signed in.|Identify event and order you need.|Use order success page for immediate confirmation.'; Steps='Find event group in My Tickets.|Move through ticket carousel and verify QR display.|Use Email Tickets resend action.|Use order success Resend Email when needed.|Use print action for offline backup.'; Dependencies='Tickets are grouped by event across orders.|Resend targets each unique order-email pair.|QR display depends on valid ticket records.|Wallet actions are placeholders in current app state.'; Access='My Tickets route is protected for parent and athlete.|Order success route is available after checkout redirect.|Resend requires valid order ID and email.'; EdgeCases='No tickets visible: verify paid order state.|Resend failed: verify email and retry once.|Multiple orders: resend handles each order.|Need manual fallback: use /portal/tickets/resend.'; DoneRight='All relevant tickets are visible and scannable.|Resend confirms successful delivery.|Gate entry can proceed without delay.' },
  [pscustomobject]@{ Title='Use Secure Ticket Access Links at the Gate'; Slug='use-secure-ticket-access-links-at-the-gate'; Section='Tickets and Entry'; Tags='tickets,access-links,qr,entry-code,gate,mobile'; Excerpt='Open secure access links and use entry code fallback if needed.'; Intro='Ticket access links are optimized for gate speed with a QR token and entry code backup.'; Before='Open full token URL exactly as delivered.|Increase brightness before scan.|Keep phone charged and unlocked.'; Steps='Open /portal/tickets/access?t=...|Wait for ticket and QR load.|Present QR to scanner.|If needed, provide manual entry code.|Keep page active through gate entry.'; Dependencies='Token must be valid and unexpired.|Wake lock may be requested for screen stability.|Entry code maps to specific ticket.|Event data is loaded from token payload.'; Access='No full portal login needed with valid token.|Invalid token shows explicit error state.|Access scope is limited to token-linked ticket data.'; EdgeCases='Expired link: request fresh access link.|Missing token: reopen exact URL.|Weak signal: preload before arrival.|Scan failure: switch to entry code immediately.'; DoneRight='QR or entry code works at gate.|You enter without reauthentication.|Ticket metadata matches event and type.' },
  [pscustomobject]@{ Title='Register for Tryouts and Track Every Status Change'; Slug='register-for-tryouts-and-track-every-status-change'; Section='Team Operations'; Tags='tryouts,registration,athletes,status,offers,families'; Excerpt='Register athletes for tryouts and follow status from signup to decision.'; Intro='Tryout workflows are high stakes, so YouthSports keeps registration and progress tracking in one place.'; Before='Open /portal/tryouts.|Verify athlete profile exists.|Review date, age group, and location.'; Steps='Select Register Now.|Choose athlete in modal and confirm.|Track status in My Tryout Progress.|If offered, choose Accept Spot or Decline.|Use registration contact for questions.'; Dependencies='Registration requires selected tryout and athlete.|Status set includes registered, offered, accepted, declined.|Offer action appears only on offered status.|Support contact comes from registration contact category.'; Access='Route requires parent or athlete and tryouts entitlement.|Athlete selector only shows your visible athletes.|Some transitions vary in demo mode.'; EdgeCases='Already registered: duplicate blocked.|No athletes: create profile first.|Registration error: retry after connection check.|No offer action: refresh and verify current status.'; DoneRight='Registration is visible in progress list.|Status changes are easy to track.|Final outcome is clearly recorded.' },
  [pscustomobject]@{ Title='Submit Uniform Orders by Athlete and Avoid Deadline Lockouts'; Slug='submit-uniform-orders-by-athlete-and-avoid-deadline-lockouts'; Section='Team Operations'; Tags='uniforms,orders,sizes,deadlines,athletes,guardians'; Excerpt='Complete required uniform sizes before kit deadlines lock orders.'; Intro='Uniform workflows succeed when required sizes are complete before deadlines and lock states change.'; Before='Open /portal/uniforms and review active kits.|Check each kit deadline and status.|Prepare sizing details for required items.'; Steps='Open View and Order on kit.|Select required item sizes per athlete.|Submit order per athlete.|Use Update Order only while editable.|Use contact card for uniform support issues.'; Dependencies='Required items must be selected to submit.|Kit can lock by deadline or lock flag.|Some statuses become immutable.|Size options come from configured kit item data.'; Access='Route requires parent or athlete and uniform entitlement.|Only your visible athletes are orderable.|Editability depends on kit status and policy.'; EdgeCases='Missing required size: complete all required fields.|Deadline passed: submissions closed.|Kit locked: edits blocked.|No athletes visible: add athlete profile first.'; DoneRight='Each athlete has valid submission.|No required items are missing.|Order status reflects submitted or updated state.' },
  [pscustomobject]@{ Title='Run Travel Day from One Travel Detail Page'; Slug='run-travel-day-from-one-travel-detail-page'; Section='Team Operations'; Tags='travel,logistics,directions,meetings,lodging,contacts'; Excerpt='Use travel detail for directions, meetings, lodging, and contacts.'; Intro='Travel Detail centralizes the actions families need on high-pressure travel days.'; Before='Open /portal/travel and select target plan.|Set commute start location.|Review meeting and schedule details early.'; Steps='Open plan detail from travel list.|Use map links and copy actions for addresses.|Save route origin for commute context.|Review schedule and add events to calendar.|Use contact panel for support channels.|Check lodging details and confirmation references.'; Dependencies='Plan status can be upcoming, active, complete, canceled.|Meeting and lodging data must be configured on plan.|Contacts resolve custom first, org fallback second.|Calendar export requires valid event date-time fields.'; Access='Travel routes require parent or athlete and travel entitlements.|Visible plans are scoped to your team context.|Contact fallback depends on org contact setup.'; EdgeCases='No route summary: verify origin and destination.|Missing contacts: fallback may be sparse.|Copy failed: check clipboard permission.|Canceled plan: follow status badge guidance.'; DoneRight='Family has confirmed route and meeting plan.|Key travel events are in calendar.|Support contacts are easy to reach.' },
  [pscustomobject]@{ Title='Use Huddles for Announcements and Team Chat'; Slug='use-huddles-for-announcements-and-team-chat'; Section='Team Operations'; Tags='huddles,messages,announcements,chat,teams,communication'; Excerpt='Read announcements and use chat channels in one Huddles workspace.'; Intro='Huddles unifies official announcements and live team chat so communication stays coherent.'; Before='Open /portal/huddles/announcements or /portal/huddles/chat.|Select correct team context.|Verify connection before expecting live updates.'; Steps='Review team announcements in announcement tab.|Open announcement detail for full context.|Switch to chat tab and choose channel.|Send messages and follow replies.|Return to announcements for official updates.'; Dependencies='Announcements can be team-specific or org-wide.|Chat requires stream connection and channels.|Channel visibility depends on team membership.|Announcement creation is role-restricted.'; Access='Route requires parent or athlete and messaging entitlement.|Guardian users consume chat and announcements.|Create announcement controls are coach/admin only.'; EdgeCases='No teams: messaging surfaces remain empty.|Chat not connecting: refresh and retry.|No announcements: confirm selected team.|Cannot create announcement: expected for guardian role.'; DoneRight='You can read current announcements.|Chat channels connect and send reliably.|No unresolved connection errors remain.' },
  [pscustomobject]@{ Title='Keep Account Settings Current for Family Logistics'; Slug='keep-account-settings-current-for-family-logistics'; Section='Account and Preferences'; Tags='settings,home-address,notifications,email,password,language,theme'; Excerpt='Update core settings so alerts, travel, and access stay reliable.'; Intro='Account settings drive travel planning, message delivery, and sign-in security more than most users expect.'; Before='Open /portal/settings.|Review address, notifications, email, and password state.|Plan to complete modal confirmations fully.'; Steps='Set or clear home address and save.|Tune notification groups, channels, digest, and quiet hours.|Change email and complete both confirmation links.|Change password with matching valid values.|Set language and theme preferences.'; Dependencies='Home address writes to profile location fields.|Notification preferences persist by org and role.|Email change requires dual confirmation path.|Password change enforces match and minimum length.'; Access='Settings route is parent and athlete accessible.|Family guardian management controls are parent-focused.|Notification groups shown depend on active role context.'; EdgeCases='Email rate limit: wait then retry.|Address save failed: use valid autocomplete selection.|Password mismatch: reenter both fields.|Notification save lag: wait for save state before exit.'; DoneRight='Address, notifications, and credentials are current.|Family settings reflect real guardian access.|No active settings errors remain.' }
)

$rows = for ($i = 0; $i -lt $articles.Count; $i++) {
  $a = $articles[$i]
  [pscustomobject]@{
    ID = ''
    Title = $a.Title
    Content = (Build-Content -a $a)
    Excerpt = $a.Excerpt
    Slug = $a.Slug
    Status = 'publish'
    Parent = ''
    Order = $i + 1
    Author = 'admin'
    Date = $date
    'Allow Comments' = 'closed'
    'Allow Pingbacks' = 'closed'
    Categories = "Help, Guardians, $($a.Section)"
    Tags = $a.Tags
    Section = $a.Section
    'Role Category' = 'Guardians'
  }
}

$outPath = Join-Path (Get-Location) 'help-center-guardian-import-20-posts.csv'
$rows | Export-Csv -Path $outPath -NoTypeInformation -Encoding UTF8

Write-Output "Wrote: $outPath"
Write-Output "Rows: $($rows.Count)"
