/**
 * Generate Type-Safe Feature Keys
 * 
 * Queries the feature_entitlements table and generates a TypeScript file
 * with a union type of all valid feature keys. This ensures compile-time
 * validation that feature keys in the registry match what exists in the DB.
 * 
 * Usage:
 *   npx tsx scripts/generate-feature-keys.ts
 * 
 * The generated file is committed to source control so CI and local dev
 * don't require a live database connection to build.
 */

import { createClient } from '@supabase/supabase-js'
import * as fs from 'fs'
import * as path from 'path'

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const SUPABASE_URL = process.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.VITE_SUPABASE_ANON_KEY

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    console.error('❌  Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY env vars')
    process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

const OUTPUT_PATH = path.resolve(__dirname, '../src/lib/featureGate/generatedFeatureKeys.ts')

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
    console.log('🔑  Fetching feature keys from database...')

    const { data: features, error } = await supabase
        .from('feature_entitlements')
        .select('feature_key, display_name, category, unavailable_gate_action, rollout_status')
        .is('archived_at', null)
        .order('feature_key', { ascending: true })

    if (error) {
        console.error('❌  Error fetching features:', error.message)
        process.exit(1)
    }

    if (!features || features.length === 0) {
        console.warn('⚠️   No features found in feature_entitlements table')
        process.exit(1)
    }

    console.log(`📋  Found ${features.length} feature(s)`)

    // -----------------------------------------------------------------------
    // Build the output
    // -----------------------------------------------------------------------

    const featureKeys = features.map(f => f.feature_key as string)

    const lines: string[] = [
        '/**',
        ' * AUTO-GENERATED — DO NOT EDIT',
        ` * Generated by scripts/generate-feature-keys.ts on ${new Date().toISOString()}`,
        ` * Source: feature_entitlements table (${features.length} features)`,
        ' *',
        ' * To regenerate:  npm run generate:feature-keys',
        ' */',
        '',
        '// ============================================================================',
        '// Feature Key Union Type',
        '// ============================================================================',
        '',
        '/**',
        ' * All valid feature keys in the database.',
        ' * Used to type-check ROUTE_TO_FEATURE and ACTION_TO_FEATURE registries.',
        ' */',
        'export type FeatureKey =',
        ...featureKeys.map((key, i) => {
            const isLast = i === featureKeys.length - 1
            return `    | '${key}'${isLast ? ';' : ''}`
        }),
        '',
        '// ============================================================================',
        '// Feature Key Set (runtime validation)',
        '// ============================================================================',
        '',
        '/** Set of all valid feature keys for runtime checks */',
        'export const VALID_FEATURE_KEYS: ReadonlySet<string> = new Set([',
        ...featureKeys.map(key => `    '${key}',`),
        ']);',
        '',
        '// ============================================================================',
        '// Feature Metadata (from DB snapshot)',
        '// ============================================================================',
        '',
        'export interface FeatureKeyMetadata {',
        '    readonly key: FeatureKey;',
        '    readonly displayName: string;',
        '    readonly category: string;',
        '    readonly gateAction: string;',
        '    readonly rolloutStatus: string;',
        '}',
        '',
        '/** Metadata for every feature key — useful for admin tooling */',
        'export const FEATURE_KEY_METADATA: ReadonlyMap<FeatureKey, FeatureKeyMetadata> = new Map([',
        ...features.map(f => {
            const key = f.feature_key as string
            const displayName = (f.display_name as string ?? '').replace(/'/g, "\\'")
            const category = (f.category as string ?? '').replace(/'/g, "\\'")
            const gateAction = f.unavailable_gate_action as string ?? 'overlay'
            const rollout = f.rollout_status as string ?? 'live'
            return `    ['${key}', { key: '${key}', displayName: '${displayName}', category: '${category}', gateAction: '${gateAction}', rolloutStatus: '${rollout}' }],`
        }),
        ']);',
        '',
        '/**',
        ' * Type guard: checks if a string is a valid FeatureKey',
        ' */',
        'export function isValidFeatureKey(key: string): key is FeatureKey {',
        '    return VALID_FEATURE_KEYS.has(key);',
        '}',
        '',
    ]

    // -----------------------------------------------------------------------
    // Write
    // -----------------------------------------------------------------------

    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })
    fs.writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8')

    console.log(`✅  Generated ${OUTPUT_PATH}`)
    console.log(`    ${featureKeys.length} feature key(s):`)
    for (const key of featureKeys) {
        const meta = features.find(f => f.feature_key === key)!
        const status = meta.rollout_status ?? 'live'
        const gate = meta.unavailable_gate_action ?? 'overlay'
        console.log(`      • ${key}  [${status}]  gate=${gate}`)
    }
}

main().catch(err => {
    console.error('❌  Unexpected error:', err)
    process.exit(1)
})
